logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[com.candylink.openvpn]
apkmirror-dlurl = "https://apkmirror.com/apk/openvpn/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"

[com.adobe.lrmobile]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"

[com.spotify.music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ltd/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"

[de.dwd.warnapp]
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"

